# generate_resources.ps1
# Converts all web frontend files into a C++ header file (web_resources.h)
# Text files → raw string literals with pre-computed lengths
# Binary files → raw byte arrays (zero runtime decode overhead)

$outputFile = "web_resources.h"
$webDir = "web"

$textFiles = @(
    @{ Name = "index_html";   File = "index.html";   ContentType = "text/html" },
    @{ Name = "splash_html";  File = "splash.html";  ContentType = "text/html" },
    @{ Name = "main_html";    File = "main.html";    ContentType = "text/html" },
    @{ Name = "program_html"; File = "program.html"; ContentType = "text/html" },
    @{ Name = "reports_html"; File = "reports.html"; ContentType = "text/html" },
    @{ Name = "run_html";     File = "run.html";     ContentType = "text/html" },
    @{ Name = "style_css";    File = "style.css";    ContentType = "text/css" },
    @{ Name = "script_js";    File = "script.js";    ContentType = "application/javascript" },
    @{ Name = "login_js";     File = "login.js";     ContentType = "application/javascript" }
)

$binaryFiles = @(
    @{ Name = "logo_png";  File = "logo.png";  ContentType = "image/png" },
    @{ Name = "logo_jpeg"; File = "logo.jpeg"; ContentType = "image/jpeg" }
)

# Use StringBuilder for fast string building
$sb = New-Object System.Text.StringBuilder 2000000

[void]$sb.AppendLine("// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY")
[void]$sb.AppendLine("// Generated by generate_resources.ps1")
[void]$sb.AppendLine("// Text files: raw string literals | Binary files: raw byte arrays (zero-copy)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <string>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace WebResources {")
[void]$sb.AppendLine("")

# Process text files
foreach ($entry in $textFiles) {
    $filePath = Join-Path $webDir $entry.File
    if (Test-Path $filePath) {
        $content = [IO.File]::ReadAllText($filePath)
        $byteLen = [System.Text.Encoding]::UTF8.GetByteCount($content)

        [void]$sb.AppendLine("static const char* $($entry.Name) = R`"RAWRES(")
        [void]$sb.Append($content)
        [void]$sb.AppendLine(")RAWRES`";")
        [void]$sb.AppendLine("static const size_t $($entry.Name)_len = $byteLen;")
        [void]$sb.AppendLine("")

        Write-Host "Embedded text: $($entry.File) ($byteLen bytes)"
    }
}

# Process binary files as raw byte arrays using batch hex conversion
foreach ($entry in $binaryFiles) {
    $filePath = Join-Path $webDir $entry.File
    if (Test-Path $filePath) {
        $bytes = [IO.File]::ReadAllBytes($filePath)

        [void]$sb.AppendLine("static const unsigned char $($entry.Name)_data[] = {")

        # Convert all bytes to hex at once using BitConverter (much faster than loop)
        $hexString = [BitConverter]::ToString($bytes).Replace("-", ",0x")
        $hexString = "0x" + $hexString

        # Insert line breaks every ~20 values for readability
        # Each entry is "0xXX," = 5 chars, 20 entries = ~100 chars per line
        $chunkSize = 100  # chars per line approximately
        $pos = 0
        while ($pos -lt $hexString.Length) {
            $end = [Math]::Min($pos + $chunkSize, $hexString.Length)
            # Find the next comma boundary to avoid splitting a hex value
            if ($end -lt $hexString.Length) {
                $commaPos = $hexString.IndexOf(",", $end)
                if ($commaPos -ge 0) { $end = $commaPos + 1 }
                else { $end = $hexString.Length }
            }
            $chunk = $hexString.Substring($pos, $end - $pos)
            [void]$sb.Append("    ")
            [void]$sb.AppendLine($chunk)
            $pos = $end
        }

        [void]$sb.AppendLine("};")
        [void]$sb.AppendLine("static const size_t $($entry.Name)_size = $($bytes.Length);")
        [void]$sb.AppendLine("")

        Write-Host "Embedded binary: $($entry.File) ($($bytes.Length) bytes as raw array)"
    }
}

# Resource lookup structure
[void]$sb.AppendLine("")
[void]$sb.AppendLine("struct Resource {")
[void]$sb.AppendLine("    const void* data;")
[void]$sb.AppendLine("    size_t dataLength;")
[void]$sb.AppendLine("    const char* contentType;")
[void]$sb.AppendLine("    bool isBinary;")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static Resource GetResource(const std::string& path) {")

foreach ($entry in $textFiles) {
    $urlPath = "/" + $entry.File
    [void]$sb.AppendLine("    if (path == `"$urlPath`") return { $($entry.Name), $($entry.Name)_len, `"$($entry.ContentType)`", false };")
}
[void]$sb.AppendLine("    if (path == `"/`") return { index_html, index_html_len, `"text/html`", false };")

foreach ($entry in $binaryFiles) {
    $urlPath = "/" + $entry.File
    [void]$sb.AppendLine("    if (path == `"$urlPath`") return { $($entry.Name)_data, $($entry.Name)_size, `"$($entry.ContentType)`", true };")
}

[void]$sb.AppendLine("    return { nullptr, 0, nullptr, false };")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("} // namespace WebResources")

[IO.File]::WriteAllText($outputFile, $sb.ToString())
Write-Host "`nGenerated $outputFile successfully!"
